BEGIN TRY
	DROP TABLE Pages
END TRY BEGIN CATCH END CATCH

CREATE TABLE Pages (
	Name varchar(128),
	Hits int
)

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN

SELECT * FROM Pages WITH (UPDLOCK) WHERE Name = 'Test'

INSERT INTO Pages (Name, Hits) VALUES ('Test', 1)

UPDATE Pages SET Hits = Hits + 1 WHERE Name = 'Test'

ROLLBACK